name: Deploy to Vercel

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '18'

jobs:
  # Job 1: Code Quality Check
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: TypeScript Type Check
        run: npm run type-check
        working-directory: ./frontend
        
      - name: ESLint Code Check
        run: npm run lint
        working-directory: ./frontend
        
      - name: Code Format Check
        run: npm run format:check
        working-directory: ./frontend
        continue-on-error: true
        
      - name: Build Verification
        run: npm run build
        working-directory: ./frontend

  # Job 2: Deploy to Production
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: quality-check
    environment: Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: Build for Production
        run: npm run build
        working-directory: ./frontend
        
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
        working-directory: ./frontend
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
