version: '3.8'

services:
  # PostgreSQL Database for Testing/CI
  postgres-test:
    container_name: laten-database-test
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'github_ci_password_2024'
      POSTGRES_DB: laten_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - '5432:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Test Server
  backend-test:
    container_name: laten-backend-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=github_ci_password_2024
      - DB_DATABASE=laten_test
      - JWT_SECRET=github_ci_jwt_secret_key_2024_super_secure
      - JWT_EXPIRES_IN=1h
      - PORT=3001
    depends_on:
      postgres-test:
        condition: service_healthy
    command: npm run test:e2e

volumes:
  postgres_test_data:
    driver: local
